### PR TITLE
fix: adding injection token to injector for getView. Fixes #5.

### LINKED ISSUE #5: Dependency Injection
Hi,

great project, but i have problems with one feature in this demo.
It seems, the dependency injection for the input character is not working.
If i run "View Reorder" the Card i tap is always undefined (CardComponent, Input).

Running on Android 10

Thank you

### PR DESCRIPTION
**Pull request by codephobia**
The GenericParams injection token was never implemented when creating the native view from the component.

### CODE REVIEW

**Comment by codephobia** [comment]
Not sure what happened with the formatting on the PR. Looks like the file might have been using 2 space tabs but editorconfig is setup to 2 spaces. The only changes made were the following in the getView method:

```ts
const injector = Injector.create({
  providers: [{ provide: GenericParams, useValue: input }],
  parent: this.injector,
});
const cmpRef = generateNativeScriptView(component, {
  injector,
});
```

**Comment by williamjuan027** [comment]
Thanks for opening a PR for this @codephobia . I was just about to look into this today, and you beat me to it :). No worries on the code formatting, I think I might have set it up incorrectly when I first started the project. I'll get the configs cleaned up so we don't run into any formatting issues in the future.

Does this address the issue outlined here https://github.com/williamjuan027/nativescript-rootlayout-demo/issues/5 ?

**Comment by codephobia** [comment]
> Thanks for opening a PR for this @codephobia . I was just about to look into this today, and you beat me to it :). No worries on the code formatting, I think I might have set it up incorrectly when I first started the project. I'll get the configs cleaned up so we don't run into any formatting issues in the future.
> 
> Does this address the issue outlined here #5 ?

Yeah, I double checked and the rick and morty characters are showing up now with the changes.

**Comment by williamjuan027** [comment]
Awesome, just merged it in. Thanks again for opening a PR for this. Really appreciate it. :)

**Pull request merged**
